title = "Jinghan Sun"
baseURL = "https://my-henrys.github.io/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Urbana, Illinois"
email = "js39-at-illinois.edu"
scholar = "js39-at-illinois.edu"
favicon = "favicon.ico"
firstName = "Jinghan"
lastName = "Sun"
phone = "1-555-555-1234"
profileImage = "img/profile_new.jpg"
showResearch = true
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = true
showMisc = true
showQr = false
showSkills = false

[params.google]

[params.google.analytics]
trackerID = "G-WZKDCVG1Y7"

[[params.handles]]
link = "https://www.linkedin.com/feed/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/my-HenryS/"
name = "GitHub"

# [[params.handles]]
# link = "https://scholar.google.com/citations?hl=en&user=6ikk4SIAAAAJ"
# name = "Scholar"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"